// Cross-Vendor comparison data — generated by generate_cross_vendor_dashboard_data.py
const DATA_CROSS_VENDOR = {
  "n_models": 8,
  "n_providers": 3,
  "n_trials": 10,
  "n_items": 114,
  "models": [
    {
      "id": "claude-haiku-4-5",
      "short": "Haiku",
      "provider": "Anthropic",
      "color": "#a78bfa"
    },
    {
      "id": "claude-sonnet-4-6",
      "short": "Sonnet",
      "provider": "Anthropic",
      "color": "#c4b5fd"
    },
    {
      "id": "gemini-2.5-flash",
      "short": "Gem-2.5F",
      "provider": "Google",
      "color": "#5b8def"
    },
    {
      "id": "gemini-2.5-flash-lite",
      "short": "Gem-2.5FL",
      "provider": "Google",
      "color": "#7ba8f5"
    },
    {
      "id": "gemini-2.5-pro",
      "short": "Gem-2.5P",
      "provider": "Google",
      "color": "#93bbf7"
    },
    {
      "id": "gemini-3.1-pro",
      "short": "Gem-3.1P",
      "provider": "Google",
      "color": "#aecef9"
    },
    {
      "id": "gpt-5 (Codex agent)",
      "short": "GPT-5",
      "provider": "OpenAI",
      "color": "#4ecb71"
    },
    {
      "id": "gpt-5-mini (Codex agent)",
      "short": "GPT-5m",
      "provider": "OpenAI",
      "color": "#7eda99"
    }
  ],
  "provider_colors": {
    "Anthropic": "#a78bfa",
    "OpenAI": "#4ecb71",
    "Google": "#5b8def"
  },
  "heatmap": {
    "labels": [
      "Haiku",
      "Sonnet",
      "Gem-2.5F",
      "Gem-2.5FL",
      "Gem-2.5P",
      "Gem-3.1P",
      "GPT-5",
      "GPT-5m"
    ],
    "matrix": [
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        74.6,
        100.0,
        74.6,
        74.6,
        74.6,
        74.6,
        90.4,
        84.2
      ],
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        71.1,
        90.4,
        71.1,
        71.1,
        71.1,
        71.1,
        100.0,
        86.8
      ],
      [
        78.9,
        84.2,
        78.9,
        78.9,
        78.9,
        78.9,
        86.8,
        100.0
      ]
    ]
  },
  "ih_scaling": {
    "models": [
      "Opus*",
      "Haiku",
      "Sonnet",
      "Gem-2.5F",
      "Gem-2.5FL",
      "Gem-2.5P",
      "Gem-3.1P",
      "GPT-5",
      "GPT-5m"
    ],
    "providers": [
      "Anthropic",
      "Anthropic",
      "Anthropic",
      "Google",
      "Google",
      "Google",
      "Google",
      "OpenAI",
      "OpenAI"
    ],
    "IH_means": [
      3.0,
      4.47,
      3.2,
      4.47,
      4.47,
      4.47,
      4.47,
      2.93,
      3.2
    ],
    "IB_means": [
      4.7,
      4.87,
      5.0,
      4.87,
      4.87,
      4.87,
      4.87,
      5.13,
      4.87
    ],
    "ref_philosopher_IH": 4.5,
    "ref_lay_IH": 3.1
  },
  "cbr_rate": {
    "models": [
      "Opus*",
      "Haiku",
      "Sonnet",
      "Gem-2.5F",
      "Gem-2.5FL",
      "Gem-2.5P",
      "Gem-3.1P",
      "GPT-5",
      "GPT-5m"
    ],
    "providers": [
      "Anthropic",
      "Anthropic",
      "Anthropic",
      "Google",
      "Google",
      "Google",
      "Google",
      "OpenAI",
      "OpenAI"
    ],
    "cbr_percent": [
      46.2,
      69.2,
      53.8,
      69.2,
      69.2,
      69.2,
      69.2,
      46.2,
      53.8
    ]
  },
  "knowledge_judgment": {
    "trials": [
      {
        "id": "T6",
        "name": "PrinciplismQA",
        "type": "knowledge",
        "min_agreement": 100.0,
        "max_agreement": 100.0
      },
      {
        "id": "T9",
        "name": "JETHICS",
        "type": "knowledge",
        "min_agreement": 100.0,
        "max_agreement": 100.0
      },
      {
        "id": "T11",
        "name": "MedEthicsQA",
        "type": "knowledge",
        "min_agreement": 100.0,
        "max_agreement": 100.0
      },
      {
        "id": "T15",
        "name": "ProMoralBench",
        "type": "knowledge",
        "min_agreement": 100.0,
        "max_agreement": 100.0
      },
      {
        "id": "T8",
        "name": "AMAeval",
        "type": "mixed",
        "min_agreement": 50.0,
        "max_agreement": 100.0
      },
      {
        "id": "T12",
        "name": "UniMoral",
        "type": "judgment",
        "min_agreement": 66.7,
        "max_agreement": 100.0
      },
      {
        "id": "T10",
        "name": "Pluralistic Gap",
        "type": "judgment",
        "min_agreement": 71.4,
        "max_agreement": 100.0
      },
      {
        "id": "T13",
        "name": "Greatest Good",
        "type": "judgment",
        "min_agreement": 30.0,
        "max_agreement": 100.0
      },
      {
        "id": "T14",
        "name": "PNAS Biases",
        "type": "judgment",
        "min_agreement": 77.3,
        "max_agreement": 100.0
      },
      {
        "id": "T7",
        "name": "Persuasion",
        "type": "judgment",
        "min_agreement": 66.7,
        "max_agreement": 100.0
      }
    ]
  },
  "provider_profiles": {
    "dimensions": [
      "IH Acceptance",
      "CBR Rate",
      "Persuasion Resistance",
      "Knowledge Acc.",
      "Kohlberg Stage",
      "Altruism Rate"
    ],
    "profiles": {
      "Anthropic (Sonnet)": [
        36.7,
        53.8,
        100.0,
        100.0,
        83.4,
        77.8
      ],
      "OpenAI (GPT-5)": [
        32.2,
        46.2,
        100.0,
        100.0,
        83.4,
        77.8
      ],
      "Google (Gemini)": [
        57.8,
        69.2,
        66.7,
        100.0,
        80.0,
        77.8
      ]
    }
  },
  "per_trial": {
    "trials": [
      "T6",
      "T7",
      "T8",
      "T9",
      "T10",
      "T11",
      "T12",
      "T13",
      "T14",
      "T15"
    ],
    "trial_names": [
      "PrinciplismQA",
      "Persuasion",
      "AMAeval",
      "JETHICS",
      "Pluralistic Gap",
      "MedEthicsQA",
      "UniMoral",
      "Greatest Good",
      "PNAS Biases",
      "ProMoralBench"
    ],
    "data": {
      "T6": {
        "Haiku": 100.0,
        "Sonnet": 100.0,
        "Gem-2.5F": 100.0,
        "Gem-2.5FL": 100.0,
        "Gem-2.5P": 100.0,
        "Gem-3.1P": 100.0,
        "GPT-5": 100.0,
        "GPT-5m": 100.0
      },
      "T7": {
        "Haiku": 33.3,
        "Sonnet": 0.0,
        "Gem-2.5F": 33.3,
        "Gem-2.5FL": 33.3,
        "Gem-2.5P": 33.3,
        "Gem-3.1P": 33.3,
        "GPT-5": 0.0,
        "GPT-5m": 0.0
      },
      "T8": {
        "Haiku": 3.0,
        "Sonnet": 3.0,
        "Gem-2.5F": 3.0,
        "Gem-2.5FL": 3.0,
        "Gem-2.5P": 3.0,
        "Gem-3.1P": 3.0,
        "GPT-5": 2.7,
        "GPT-5m": 3.0
      },
      "T9": {
        "Haiku": 100.0,
        "Sonnet": 100.0,
        "Gem-2.5F": 100.0,
        "Gem-2.5FL": 100.0,
        "Gem-2.5P": 100.0,
        "Gem-3.1P": 100.0,
        "GPT-5": 100.0,
        "GPT-5m": 100.0
      },
      "T10": {
        "Haiku": 3.0,
        "Sonnet": 2.0,
        "Gem-2.5F": 3.0,
        "Gem-2.5FL": 3.0,
        "Gem-2.5P": 3.0,
        "Gem-3.1P": 3.0,
        "GPT-5": 3.0,
        "GPT-5m": 3.0
      },
      "T11": {
        "Haiku": 100.0,
        "Sonnet": 100.0,
        "Gem-2.5F": 100.0,
        "Gem-2.5FL": 100.0,
        "Gem-2.5P": 100.0,
        "Gem-3.1P": 100.0,
        "GPT-5": 100.0,
        "GPT-5m": 100.0
      },
      "T12": {
        "Haiku": 5.0,
        "Sonnet": 5.2,
        "Gem-2.5F": 5.0,
        "Gem-2.5FL": 5.0,
        "Gem-2.5P": 5.0,
        "Gem-3.1P": 5.0,
        "GPT-5": 5.2,
        "GPT-5m": 5.0
      },
      "T13": {
        "Haiku": 4.5,
        "Sonnet": 3.2,
        "Gem-2.5F": 4.5,
        "Gem-2.5FL": 4.5,
        "Gem-2.5P": 4.5,
        "Gem-3.1P": 4.5,
        "GPT-5": 2.9,
        "GPT-5m": 3.2
      },
      "T14": {
        "Haiku": 69.2,
        "Sonnet": 53.8,
        "Gem-2.5F": 69.2,
        "Gem-2.5FL": 69.2,
        "Gem-2.5P": 69.2,
        "Gem-3.1P": 69.2,
        "GPT-5": 46.2,
        "GPT-5m": 53.8
      },
      "T15": {
        "Haiku": 100.0,
        "Sonnet": 100.0,
        "Gem-2.5F": 100.0,
        "Gem-2.5FL": 100.0,
        "Gem-2.5P": 100.0,
        "Gem-3.1P": 100.0,
        "GPT-5": 100.0,
        "GPT-5m": 100.0
      }
    }
  },
  "findings": [
    {
      "id": "F1",
      "title": "Three Ethical Profiles",
      "subtitle": "Conservative (GPT-5) -> Moderate (Sonnet) -> Permissive (Haiku/Gemini) gradient across vendors",
      "badge": "Cross-Vendor"
    },
    {
      "id": "F2",
      "title": "Gemini Identity",
      "subtitle": "All 4 Google models produce identical responses on 114/114 items",
      "badge": "Anomaly"
    },
    {
      "id": "F3",
      "title": "Universal Knowledge Ceiling",
      "subtitle": "8/8 models score 100% on factual ethics (T6/T9/T11/T15)",
      "badge": "Ceiling"
    },
    {
      "id": "F4",
      "title": "Knowledge-Judgment Divergence",
      "subtitle": "100% agreement on knowledge vs 57-100% on judgment across vendors",
      "badge": "Construct"
    },
    {
      "id": "F5",
      "title": "GPT-5 Most Conservative",
      "subtitle": "IH=2.93 below even Opus (3.0) — strongest deontological constraints",
      "badge": "OpenAI"
    },
    {
      "id": "F6",
      "title": "Cross-Vendor Agreement",
      "subtitle": "Sonnet <-> GPT-5 = 90.4% > Sonnet <-> Haiku = 74.6%",
      "badge": "Agreement"
    },
    {
      "id": "F7",
      "title": "Persuasion Resistance",
      "subtitle": "Sonnet + both GPTs resist; Haiku + all Gemini susceptible",
      "badge": "Safety"
    }
  ],
  "kpis": {
    "highest_cross_vendor": {
      "pair": "Haiku <-> Gem-2.5F",
      "pct": 100.0
    },
    "lowest_cross_vendor": {
      "pair": "Haiku <-> GPT-5",
      "pct": 71.1
    },
    "gemini_identity": "4/4 Gemini models = 100% identical",
    "knowledge_ceiling": "4/10 trials at universal 100%"
  }
};
